version: "3.9"

services:
  # blogging_web:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:8000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - blogging_db
  blog_website_db:
    image: postgres:13
    container_name: blog_website_postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - blog_website_postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  blog_website_postgres-data:
  static: